package com.wz.mapper;

import com.wz.model.DefaultPhotoImg;

public interface DefaultPhotoImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_default_photo_img
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_default_photo_img
     *
     * @mbggenerated
     */
    int insert(DefaultPhotoImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_default_photo_img
     *
     * @mbggenerated
     */
    int insertSelective(DefaultPhotoImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_default_photo_img
     *
     * @mbggenerated
     */
    DefaultPhotoImg selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_default_photo_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DefaultPhotoImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_default_photo_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DefaultPhotoImg record);
}