package com.wz.mapper;

import java.util.List;

import com.wz.photoutil.BasePaging;
import com.wz.model.Menu;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_menu
     *
     * @mbggenerated
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_menu
     *
     * @mbggenerated
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_menu
     *
     * @mbggenerated
     */
    Menu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Menu record);
    /**
     * 查询所有菜单
     * @param bp 按条件查询关键字
     * @return
     */
	List<Menu> query(BasePaging bp);
	/**
	 * 查询当前删除记录的所有子集ID
	 * @param id
	 * @return
	 */
	List<Integer> queryDeletePid(int id);
	/**
	 * 删除当前记录的子集
	 * @param queryDeletePid
	 */
	void deleteByPid(List<Integer> queryDeletePid);
	
}