package com.wz.mapper;

import java.util.List;

import com.wz.model.Template;
import com.wz.photoutil.BasePaging;

public interface TemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template
     *
     * @mbggenerated
     */
    int insert(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template
     *
     * @mbggenerated
     */
    int insertSelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template
     *
     * @mbggenerated
     */
    Template selectByPrimaryKey(Integer templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Template record);
    /**
     * 查询所有模板
     * @return
     */
    List<Template> selectAll(BasePaging bp);
    /**
     * 根据风格查询模板
     * @param bp
     * @param styleId
     * @return
     */
	List<Template> selectByTemplateStyle(BasePaging bp, int styleId);
	/**
	 * 根据ID查询
	 * @param id
	 * @return
	 */
	Template selectById(int id);
	/**
	 * 根据ID删除模板
	 * @param id
	 */
	void deleteById(int id);
	/**
	 * 根据风格删除模板
	 * @param id
	 */
	void deleteByTemplateStyleId(int id);
	
}