package com.wz.mapper;

import java.util.List;

import com.wz.model.Trim;

public interface TrimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_trim
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer trimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_trim
     *
     * @mbggenerated
     */
    int insert(Trim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_trim
     *
     * @mbggenerated
     */
    int insertSelective(Trim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_trim
     *
     * @mbggenerated
     */
    Trim selectByPrimaryKey(Integer trimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_trim
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Trim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_trim
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Trim record);

	List<com.wz.model.Trim> select(Trim trim);
}