package com.wz.mapper;

import java.util.List;

import com.wz.photoutil.BasePaging;
import com.wz.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
    /**
     * 查询所有用户
     * @param bp 按条件查询关键字
     * @return
     */
    List<User> query(BasePaging bp);
    /**
     * 用户登录
     * @param username
     * @return
     */
	User login(String username);
}