package com.wz.model;

public class CustomerImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_customer_img.cus_img_id
     *
     * @mbggenerated
     */
    private String cusImgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_customer_img.cus_img_oldfilename
     *
     * @mbggenerated
     */
    private String cusImgOldfilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_customer_img.cus_img_date
     *
     * @mbggenerated
     */
    private String cusImgDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_customer_img.cus_img_format
     *
     * @mbggenerated
     */
    private String cusImgFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_customer_img.cus_img_path
     *
     * @mbggenerated
     */
    private String cusImgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_customer_img.cus_img_url
     *
     * @mbggenerated
     */
    private String cusImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_customer_img.cus_img_pid
     *
     * @mbggenerated
     */
    private String cusImgPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_customer_img.cus_img_newfilename
     *
     * @mbggenerated
     */
    private String cusImgNewfilename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_customer_img.cus_img_id
     *
     * @return the value of ph_customer_img.cus_img_id
     *
     * @mbggenerated
     */
    public String getCusImgId() {
        return cusImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_customer_img.cus_img_id
     *
     * @param cusImgId the value for ph_customer_img.cus_img_id
     *
     * @mbggenerated
     */
    public void setCusImgId(String cusImgId) {
        this.cusImgId = cusImgId == null ? null : cusImgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_customer_img.cus_img_oldfilename
     *
     * @return the value of ph_customer_img.cus_img_oldfilename
     *
     * @mbggenerated
     */
    public String getCusImgOldfilename() {
        return cusImgOldfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_customer_img.cus_img_oldfilename
     *
     * @param cusImgOldfilename the value for ph_customer_img.cus_img_oldfilename
     *
     * @mbggenerated
     */
    public void setCusImgOldfilename(String cusImgOldfilename) {
        this.cusImgOldfilename = cusImgOldfilename == null ? null : cusImgOldfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_customer_img.cus_img_date
     *
     * @return the value of ph_customer_img.cus_img_date
     *
     * @mbggenerated
     */
    public String getCusImgDate() {
        return cusImgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_customer_img.cus_img_date
     *
     * @param cusImgDate the value for ph_customer_img.cus_img_date
     *
     * @mbggenerated
     */
    public void setCusImgDate(String cusImgDate) {
        this.cusImgDate = cusImgDate == null ? null : cusImgDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_customer_img.cus_img_format
     *
     * @return the value of ph_customer_img.cus_img_format
     *
     * @mbggenerated
     */
    public String getCusImgFormat() {
        return cusImgFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_customer_img.cus_img_format
     *
     * @param cusImgFormat the value for ph_customer_img.cus_img_format
     *
     * @mbggenerated
     */
    public void setCusImgFormat(String cusImgFormat) {
        this.cusImgFormat = cusImgFormat == null ? null : cusImgFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_customer_img.cus_img_path
     *
     * @return the value of ph_customer_img.cus_img_path
     *
     * @mbggenerated
     */
    public String getCusImgPath() {
        return cusImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_customer_img.cus_img_path
     *
     * @param cusImgPath the value for ph_customer_img.cus_img_path
     *
     * @mbggenerated
     */
    public void setCusImgPath(String cusImgPath) {
        this.cusImgPath = cusImgPath == null ? null : cusImgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_customer_img.cus_img_url
     *
     * @return the value of ph_customer_img.cus_img_url
     *
     * @mbggenerated
     */
    public String getCusImgUrl() {
        return cusImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_customer_img.cus_img_url
     *
     * @param cusImgUrl the value for ph_customer_img.cus_img_url
     *
     * @mbggenerated
     */
    public void setCusImgUrl(String cusImgUrl) {
        this.cusImgUrl = cusImgUrl == null ? null : cusImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_customer_img.cus_img_pid
     *
     * @return the value of ph_customer_img.cus_img_pid
     *
     * @mbggenerated
     */
    public String getCusImgPid() {
        return cusImgPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_customer_img.cus_img_pid
     *
     * @param cusImgPid the value for ph_customer_img.cus_img_pid
     *
     * @mbggenerated
     */
    public void setCusImgPid(String cusImgPid) {
        this.cusImgPid = cusImgPid == null ? null : cusImgPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_customer_img.cus_img_newfilename
     *
     * @return the value of ph_customer_img.cus_img_newfilename
     *
     * @mbggenerated
     */
    public String getCusImgNewfilename() {
        return cusImgNewfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_customer_img.cus_img_newfilename
     *
     * @param cusImgNewfilename the value for ph_customer_img.cus_img_newfilename
     *
     * @mbggenerated
     */
    public void setCusImgNewfilename(String cusImgNewfilename) {
        this.cusImgNewfilename = cusImgNewfilename == null ? null : cusImgNewfilename.trim();
    }
}