package com.wz.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_menu.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_menu.menu_name
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_menu.menu_link
     *
     * @mbggenerated
     */
    private String menuLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_menu.menu_pid
     *
     * @mbggenerated
     */
    private Integer menuPid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_menu.menu_id
     *
     * @return the value of ph_menu.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_menu.menu_id
     *
     * @param menuId the value for ph_menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_menu.menu_name
     *
     * @return the value of ph_menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_menu.menu_name
     *
     * @param menuName the value for ph_menu.menu_name
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_menu.menu_link
     *
     * @return the value of ph_menu.menu_link
     *
     * @mbggenerated
     */
    public String getMenuLink() {
        return menuLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_menu.menu_link
     *
     * @param menuLink the value for ph_menu.menu_link
     *
     * @mbggenerated
     */
    public void setMenuLink(String menuLink) {
        this.menuLink = menuLink == null ? null : menuLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_menu.menu_pid
     *
     * @return the value of ph_menu.menu_pid
     *
     * @mbggenerated
     */
    public Integer getMenuPid() {
        return menuPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_menu.menu_pid
     *
     * @param menuPid the value for ph_menu.menu_pid
     *
     * @mbggenerated
     */
    public void setMenuPid(Integer menuPid) {
        this.menuPid = menuPid;
    }
}