package com.wz.model;

public class Template {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_template.template_id
     *
     * @mbggenerated
     */
    private Integer templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_template.template_name
     *
     * @mbggenerated
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_template.template_style_id
     *
     * @mbggenerated
     */
    private Integer templateStyleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_template.template_id
     *
     * @return the value of ph_template.template_id
     *
     * @mbggenerated
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_template.template_id
     *
     * @param templateId the value for ph_template.template_id
     *
     * @mbggenerated
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_template.template_name
     *
     * @return the value of ph_template.template_name
     *
     * @mbggenerated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_template.template_name
     *
     * @param templateName the value for ph_template.template_name
     *
     * @mbggenerated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_template.template_style_id
     *
     * @return the value of ph_template.template_style_id
     *
     * @mbggenerated
     */
    public Integer getTemplateStyleId() {
        return templateStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_template.template_style_id
     *
     * @param templateStyleId the value for ph_template.template_style_id
     *
     * @mbggenerated
     */
    public void setTemplateStyleId(Integer templateStyleId) {
        this.templateStyleId = templateStyleId;
    }

	@Override
	public String toString() {
		return "Template [templateId=" + templateId + ", templateName=" + templateName + ", templateStyleId="
				+ templateStyleId + "]";
	}
}