package com.wz.model;

public class TrimType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_ornament_type.trimtype_id
     *
     * @mbggenerated
     */
    private Integer trimtypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_ornament_type.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_ornament_type.trimtype_id
     *
     * @return the value of ph_ornament_type.trimtype_id
     *
     * @mbggenerated
     */
    public Integer getTrimtypeId() {
        return trimtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_ornament_type.trimtype_id
     *
     * @param trimtypeId the value for ph_ornament_type.trimtype_id
     *
     * @mbggenerated
     */
    public void setTrimtypeId(Integer trimtypeId) {
        this.trimtypeId = trimtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_ornament_type.memo
     *
     * @return the value of ph_ornament_type.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_ornament_type.memo
     *
     * @param memo the value for ph_ornament_type.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}