package com.wz.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_phone
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_wx
     *
     * @mbggenerated
     */
    private String userWx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_qq
     *
     * @mbggenerated
     */
    private String userQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_realname
     *
     * @mbggenerated
     */
    private String userRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_address
     *
     * @mbggenerated
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_pid
     *
     * @mbggenerated
     */
    private Integer userPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_level
     *
     * @mbggenerated
     */
    private Byte userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_ip
     *
     * @mbggenerated
     */
    private String userIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_user.user_date
     *
     * @mbggenerated
     */
    private Date userDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_id
     *
     * @return the value of ph_user.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_id
     *
     * @param userId the value for ph_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_name
     *
     * @return the value of ph_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_name
     *
     * @param userName the value for ph_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_password
     *
     * @return the value of ph_user.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_password
     *
     * @param userPassword the value for ph_user.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_phone
     *
     * @return the value of ph_user.user_phone
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_phone
     *
     * @param userPhone the value for ph_user.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_wx
     *
     * @return the value of ph_user.user_wx
     *
     * @mbggenerated
     */
    public String getUserWx() {
        return userWx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_wx
     *
     * @param userWx the value for ph_user.user_wx
     *
     * @mbggenerated
     */
    public void setUserWx(String userWx) {
        this.userWx = userWx == null ? null : userWx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_qq
     *
     * @return the value of ph_user.user_qq
     *
     * @mbggenerated
     */
    public String getUserQq() {
        return userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_qq
     *
     * @param userQq the value for ph_user.user_qq
     *
     * @mbggenerated
     */
    public void setUserQq(String userQq) {
        this.userQq = userQq == null ? null : userQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_realname
     *
     * @return the value of ph_user.user_realname
     *
     * @mbggenerated
     */
    public String getUserRealname() {
        return userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_realname
     *
     * @param userRealname the value for ph_user.user_realname
     *
     * @mbggenerated
     */
    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname == null ? null : userRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_address
     *
     * @return the value of ph_user.user_address
     *
     * @mbggenerated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_address
     *
     * @param userAddress the value for ph_user.user_address
     *
     * @mbggenerated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_pid
     *
     * @return the value of ph_user.user_pid
     *
     * @mbggenerated
     */
    public Integer getUserPid() {
        return userPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_pid
     *
     * @param userPid the value for ph_user.user_pid
     *
     * @mbggenerated
     */
    public void setUserPid(Integer userPid) {
        this.userPid = userPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_level
     *
     * @return the value of ph_user.user_level
     *
     * @mbggenerated
     */
    public Byte getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_level
     *
     * @param userLevel the value for ph_user.user_level
     *
     * @mbggenerated
     */
    public void setUserLevel(Byte userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_ip
     *
     * @return the value of ph_user.user_ip
     *
     * @mbggenerated
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_ip
     *
     * @param userIp the value for ph_user.user_ip
     *
     * @mbggenerated
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp == null ? null : userIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_user.user_date
     *
     * @return the value of ph_user.user_date
     *
     * @mbggenerated
     */
    public Date getUserDate() {
        return userDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_user.user_date
     *
     * @param userDate the value for ph_user.user_date
     *
     * @mbggenerated
     */
    public void setUserDate(Date userDate) {
        this.userDate = userDate;
    }
}