package com.wz.mapper;

import com.wz.model.CustomerImg;

public interface CustomerImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_customer_img
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cusImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_customer_img
     *
     * @mbggenerated
     */
    int insert(CustomerImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_customer_img
     *
     * @mbggenerated
     */
    int insertSelective(CustomerImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_customer_img
     *
     * @mbggenerated
     */
    CustomerImg selectByPrimaryKey(String cusImgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_customer_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_customer_img
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerImg record);
}