package com.wz.mapper;

import java.util.List;

import com.wz.model.TemplateStyle;

public interface TemplateStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template_style
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer styleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template_style
     *
     * @mbggenerated
     */
    int insert(TemplateStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template_style
     *
     * @mbggenerated
     */
    int insertSelective(TemplateStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template_style
     *
     * @mbggenerated
     */
    TemplateStyle selectByPrimaryKey(Integer styleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template_style
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TemplateStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ph_template_style
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TemplateStyle record);
    /**
     * 查询所有风格
     * @return
     */
	List<TemplateStyle> selectAll();
	/**
	 * 删除风格
	 * @param id
	 */
	void deleteById(int id);
}