package com.wz.model;

import java.util.Date;

public class DefaultPhotoImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_default_photo_img.img_id
     *
     * @mbggenerated
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_default_photo_img.img_name
     *
     * @mbggenerated
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_default_photo_img.img_date
     *
     * @mbggenerated
     */
    private Date imgDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_default_photo_img.img_format
     *
     * @mbggenerated
     */
    private String imgFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_default_photo_img.img_path
     *
     * @mbggenerated
     */
    private String imgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_default_photo_img.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_default_photo_img.img_template_pid
     *
     * @mbggenerated
     */
    private String imgTemplatePid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_default_photo_img.img_id
     *
     * @return the value of ph_default_photo_img.img_id
     *
     * @mbggenerated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_default_photo_img.img_id
     *
     * @param imgId the value for ph_default_photo_img.img_id
     *
     * @mbggenerated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_default_photo_img.img_name
     *
     * @return the value of ph_default_photo_img.img_name
     *
     * @mbggenerated
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_default_photo_img.img_name
     *
     * @param imgName the value for ph_default_photo_img.img_name
     *
     * @mbggenerated
     */
    public void setImgName(String imgName) {
        this.imgName = imgName == null ? null : imgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_default_photo_img.img_date
     *
     * @return the value of ph_default_photo_img.img_date
     *
     * @mbggenerated
     */
    public Date getImgDate() {
        return imgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_default_photo_img.img_date
     *
     * @param imgDate the value for ph_default_photo_img.img_date
     *
     * @mbggenerated
     */
    public void setImgDate(Date imgDate) {
        this.imgDate = imgDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_default_photo_img.img_format
     *
     * @return the value of ph_default_photo_img.img_format
     *
     * @mbggenerated
     */
    public String getImgFormat() {
        return imgFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_default_photo_img.img_format
     *
     * @param imgFormat the value for ph_default_photo_img.img_format
     *
     * @mbggenerated
     */
    public void setImgFormat(String imgFormat) {
        this.imgFormat = imgFormat == null ? null : imgFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_default_photo_img.img_path
     *
     * @return the value of ph_default_photo_img.img_path
     *
     * @mbggenerated
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_default_photo_img.img_path
     *
     * @param imgPath the value for ph_default_photo_img.img_path
     *
     * @mbggenerated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_default_photo_img.img_url
     *
     * @return the value of ph_default_photo_img.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_default_photo_img.img_url
     *
     * @param imgUrl the value for ph_default_photo_img.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_default_photo_img.img_template_pid
     *
     * @return the value of ph_default_photo_img.img_template_pid
     *
     * @mbggenerated
     */
    public String getImgTemplatePid() {
        return imgTemplatePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_default_photo_img.img_template_pid
     *
     * @param imgTemplatePid the value for ph_default_photo_img.img_template_pid
     *
     * @mbggenerated
     */
    public void setImgTemplatePid(String imgTemplatePid) {
        this.imgTemplatePid = imgTemplatePid == null ? null : imgTemplatePid.trim();
    }
}