package com.wz.model;

public class TemplateStyle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_template_style.style_id
     *
     * @mbggenerated
     */
    private Integer styleId;

    

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_template_style.style_name
     *
     * @mbggenerated
     */
    private String styleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_template_style.style_number
     *
     * @mbggenerated
     */
    private Integer styleNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_template_style.style_id
     *
     * @return the value of ph_template_style.style_id
     *
     * @mbggenerated
     */
    public Integer getStyleId() {
        return styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_template_style.style_id
     *
     * @param styleId the value for ph_template_style.style_id
     *
     * @mbggenerated
     */
    public void setStyleId(Integer styleId) {
        this.styleId = styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_template_style.style_name
     *
     * @return the value of ph_template_style.style_name
     *
     * @mbggenerated
     */
    public String getStyleName() {
        return styleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_template_style.style_name
     *
     * @param styleName the value for ph_template_style.style_name
     *
     * @mbggenerated
     */
    public void setStyleName(String styleName) {
        this.styleName = styleName == null ? null : styleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_template_style.style_number
     *
     * @return the value of ph_template_style.style_number
     *
     * @mbggenerated
     */
    public Integer getStyleNumber() {
        return styleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_template_style.style_number
     *
     * @param styleNumber the value for ph_template_style.style_number
     *
     * @mbggenerated
     */
    public void setStyleNumber(Integer styleNumber) {
        this.styleNumber = styleNumber;
    }
    
    @Override
	public String toString() {
		return "TemplateStyle [styleId=" + styleId + ", styleName=" + styleName + ", styleNumber=" + styleNumber + "]";
	}
}