package com.wz.model;

public class Trim {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_trim.trim_id
     *
     * @mbggenerated
     */
    private Integer trimId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_trim.trim_type
     *
     * @mbggenerated
     */
    private Integer trimType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_trim.trim_name
     *
     * @mbggenerated
     */
    private String trimName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_trim.trim_path
     *
     * @mbggenerated
     */
    private String trimPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_trim.trim_format
     *
     * @mbggenerated
     */
    private String trimFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_trim.trim_oldFileName
     *
     * @mbggenerated
     */
    private String trimOldfilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ph_trim.trim_newFileName
     *
     * @mbggenerated
     */
    private String trimNewfilename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_trim.trim_id
     *
     * @return the value of ph_trim.trim_id
     *
     * @mbggenerated
     */
    public Integer getTrimId() {
        return trimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_trim.trim_id
     *
     * @param trimId the value for ph_trim.trim_id
     *
     * @mbggenerated
     */
    public void setTrimId(Integer trimId) {
        this.trimId = trimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_trim.trim_type
     *
     * @return the value of ph_trim.trim_type
     *
     * @mbggenerated
     */
    public Integer getTrimType() {
        return trimType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_trim.trim_type
     *
     * @param trimType the value for ph_trim.trim_type
     *
     * @mbggenerated
     */
    public void setTrimType(Integer trimType) {
        this.trimType = trimType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_trim.trim_name
     *
     * @return the value of ph_trim.trim_name
     *
     * @mbggenerated
     */
    public String getTrimName() {
        return trimName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_trim.trim_name
     *
     * @param trimName the value for ph_trim.trim_name
     *
     * @mbggenerated
     */
    public void setTrimName(String trimName) {
        this.trimName = trimName == null ? null : trimName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_trim.trim_path
     *
     * @return the value of ph_trim.trim_path
     *
     * @mbggenerated
     */
    public String getTrimPath() {
        return trimPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_trim.trim_path
     *
     * @param trimPath the value for ph_trim.trim_path
     *
     * @mbggenerated
     */
    public void setTrimPath(String trimPath) {
        this.trimPath = trimPath == null ? null : trimPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_trim.trim_format
     *
     * @return the value of ph_trim.trim_format
     *
     * @mbggenerated
     */
    public String getTrimFormat() {
        return trimFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_trim.trim_format
     *
     * @param trimFormat the value for ph_trim.trim_format
     *
     * @mbggenerated
     */
    public void setTrimFormat(String trimFormat) {
        this.trimFormat = trimFormat == null ? null : trimFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_trim.trim_oldFileName
     *
     * @return the value of ph_trim.trim_oldFileName
     *
     * @mbggenerated
     */
    public String getTrimOldfilename() {
        return trimOldfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_trim.trim_oldFileName
     *
     * @param trimOldfilename the value for ph_trim.trim_oldFileName
     *
     * @mbggenerated
     */
    public void setTrimOldfilename(String trimOldfilename) {
        this.trimOldfilename = trimOldfilename == null ? null : trimOldfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ph_trim.trim_newFileName
     *
     * @return the value of ph_trim.trim_newFileName
     *
     * @mbggenerated
     */
    public String getTrimNewfilename() {
        return trimNewfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ph_trim.trim_newFileName
     *
     * @param trimNewfilename the value for ph_trim.trim_newFileName
     *
     * @mbggenerated
     */
    public void setTrimNewfilename(String trimNewfilename) {
        this.trimNewfilename = trimNewfilename == null ? null : trimNewfilename.trim();
    }
}